name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with the name of your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install  # Replace with the command to install dependencies for your project

    - name: Build project
      run: npm run build  # Replace with the command to build your project

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}  # Replace with your personal access token
        publish_dir: ./build  # Replace with the directory containing your compiled project
